# Font
[font]
size = 11.25
# geist
# normal = { fmaily = "GeistMono NFM", style = "Regular" }
# minecraft
# normal = { family = "Monocraft Nerd Font", style = "Book" }

# Window
[window]
opacity=0.90
blur=true
dynamic_padding = true

# Tokyo Night
  [colors.bright]
  black = "#444b6a"
  blue = "#7da6ff"
  cyan = "#0db9d7"
  green = "#b9f27c"
  magenta = "#bb9af7"
  red = "#ff7a93"
  white = "#acb0d0"
  yellow = "#ff9e64"

  [colors.normal]
  black = "#32344a"
  blue = "#7aa2f7"
  cyan = "#449dab"
  green = "#9ece6a"
  magenta = "#ad8ee6"
  red = "#f7768e"
  white = "#787c99"
  yellow = "#e0af68"

  [colors.primary]
  background = "#1a1b26"
  foreground = "#a9b1d6"


# Terminal
[terminal]

[env]
TERM = "xterm-256color"

# Debian
[terminal.shell]
program = "debian"

