# ~/.config/tmux-sessionizer/tmux-sessionizer.conf

# default directories that tmux-sessionizer will use

# Defines the primary directories to search for projects.
# This overrides the script's default search paths.
TS_SEARCH_PATHS=(
  ~/Code/projs/current
  # ~/Code/projs/current
  # ~/Code/clubs:2 # example: search '~/Code/clubs' up to 2 directories deep.
)

# Adds additional search paths to `TS_SEARCH_PATHS`.
# Paths can include `:number` to specify a search depth for that path.
TS_EXTRA_SEARCH_PATHS=(
)

# Specifies exact directories to include as session options.
# These paths are added directly and not recursively searched.
TS_SPECIFIC_PATHS=(
  ~/.config
  ~/.config/dotfiles
  ~/.config/nvim

  ~/Code
  ~/Code/projs
  ~/Code/old-rebel-hacks
  ~/Code/projs/portfolio/v3
  ~/Code/projs/rebel-hacks
  ~/Personal/resume

  ~/School/junior/spring
  ~/School/junior/spring/CS472/fomo
)
